### ISSUE TITLE
Can we use different prompts to different frames？

### ISSUE THREAD

**Issue by L0veYurisa** [Kosinkadink/ComfyUI-Advanced-ControlNet#10]
I want to use smiling prompts for frames 1-4 and closed eye prompts for frames 5-16. Can that be done?

**Comment by Kosinkadink** [comment]
That can be done using [FizzNode's](https://github.com/FizzleDorf/ComfyUI_FizzNodes) BatchPromptSchedule node, and this technique is known as "prompt travel". There are some "prompt travel" examples in the [AnimateDiff-Evolved](https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved) README.
