### ISSUE TITLE
No mask_optional on Advanced Apply

### ISSUE THREAD

**Issue by worthy7** [Kosinkadink/ComfyUI-Advanced-ControlNet#103]
Maybe I am doing something very wrong. I have comfyUI and the manager, and it seems this repo is automatically installed and managed.

![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/4762399/4a93b818-a939-4b02-9ec6-e3a6f066c20c)

But, I do not have all the inputs that are shown in the readme. Mine shows like this:
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/4762399/e40f8c34-9e0f-406b-8e2e-680afd99269c)

**Comment by Kosinkadink** [comment]
The node you have pictured there is the vanilla ComfyUI controlnet node. All ComfyUI-Advanced-ControlNet nodes are in the Adv-ControlNet sub menu in the nodes (with the blue sign with man holding a hand up emoji).

**Comment by worthy7** [comment]
Got it thanks. Perhaps this stuff should be deleted from the vanilla comfy since it cannot be updated...
