### ISSUE TITLE
Error occurred when executing LoadImagesFromDirectory

### ISSUE THREAD

**Issue by IGZIHE** [Kosinkadink/ComfyUI-Advanced-ControlNet#107]
Hello, when I use the "Load Images " node, it cannot load my image and reports an error: Path not found. I am very confused. I hope you can help me solve this problem. Thank you very much.
My path: "F:\\comfyui\\image\\to.jpg";
![1](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/53031246/8030bd98-3939-4d1d-aab0-5814b8b96906)
![2](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/53031246/da7a5ff4-1ae8-41f3-b4fc-8efab15b893b)

**Comment by Kosinkadink** [comment]
As the node name states, this node is deprecated and no further development will happen on it (it has been deprecated for over 6 months now). Use VodeoHelperSuite's Load Images (Path) instead.

**Comment by IGZIHE** [comment]
I'm very sorry that I ignored this prompt. Can you tell me where the VideoHelperSuite node is?

**Comment by Kosinkadink** [comment]
Also, the deprecated node still works - however it is intended to load images from a directory, not a single file. You provided a single file, so that's why it didn't work.

VideoHelperSuite is a node pack, you can get it from the comfyui manager.

**Comment by IGZIHE** [comment]
Ok thank you very much, but I have a question, as you said, although it has been deprecated but you can load the folder, then how should I write the folder path?

**Comment by Kosinkadink** [comment]
Just remove the file name from the end, so remove the "to.jpg"

**Comment by IGZIHE** [comment]
Thank you very much for your help, but it prompts:
cannot identify image file 'F:\\comfyui\\image\\1.mp4'
Are there any format requirements for videos, including the VideoHelperSuite node you developed?

**Comment by Kosinkadink** [comment]
I think you are misunderstanding how the node works. You are supposed to provide a path to a folder, not a file.

**Comment by IGZIHE** [comment]
Here's the thing, I provided a folder path, but the prompt it gave me was:
cannot identify image file 'F:\comfyui\image\1.mp4'
Show you my screenshot:
![3](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/53031246/114ef2ae-3962-4a9a-92a6-2ce0dc5e6c7a)
As shown in the picture, I provided a folder path instead of a specific file, but it prompted an error: cannot identify image file 'F:\comfyui\image\1.mp4', which should not be able to parse me. video?

**Comment by Kosinkadink** [comment]
The deprecated node likely requires that only image files are in the folder. The VideoHelperSuite version might be able to automatically ignore non-image files.

**Comment by IGZIHE** [comment]
Okay, thank you very much for your help. As you said, VideoHelperSuite node is very useful！
