### ISSUE TITLE
[PSA] If using SparseCtrl, new ComfyUI update requires Advanced-ControlNet to be updated, otherwise you'll get a model_keys issue

### ISSUE THREAD

**Issue by Kosinkadink** [Kosinkadink/ComfyUI-Advanced-ControlNet#119]
Simply update to newest Advanced-ControlNet, and you're good to go. Is backwards compatible with old ComfyUI versions, so no worries.

**Comment by FizzleDorf** [comment]
Just having strange behaviour with older workflows. The nodes need to be manually replaced after updating in some cases.
