### ISSUE TITLE
[Steerable Motion Fix] AttributeError: 'str' object has no attribute 'get_indexes' #80

### ISSUE THREAD

**Issue by peteromallet** [Kosinkadink/ComfyUI-Advanced-ControlNet#120]
I updated Steerable Motion to fix an issue and in doing so righted a very stupid decision I made a while back - basically, I could've just been passing values to Advanced Controlnet instead of processing it inside my code.

The downside of me fixing is that this will break existing workflows - to fix them, you just need to **plug Keyframe Positions into a SparseCtrl Index Method node** like I do here https://github.com/banodoco/Steerable-Motion/blob/main/demo/creative_interpolation_example.json

While you're doing this, I would also highly recommend you explore the other Steerable Motion workflows linked here - they have the issue fixed: https://github.com/banodoco/Steerable-Motion?tab=readme-ov-file#5-basic-workflows-to-get-started

You **may need to re-insert the Batch Creative Interpolation node** so it updates the type of output and can plug into SparseCtrl Index Method.

To be clear, this is **not Kosinkadink's fault** - it's my own stupidity. Please direct any confusion or issues towards me: https://github.com/banodoco/Steerable-Motion

**Comment by Kosinkadink** [comment]
I've updated Advanced-ControlNet to now automatically handle the outdated workflows, so updating Advanced-ControlNet (and Steerable-Motion) will resolve the issue.
