### ISSUE TITLE
Type 'ControlLLLiteAdvanced' must be used with Apply Advanced ControlNet 🛂🅐🅒🅝 node (with model_optional passed in); otherwise, it will not work

### ISSUE THREAD

**Issue by kkget** [Kosinkadink/ComfyUI-Advanced-ControlNet#121]
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/40913168/f5391fda-7bb1-4b3d-b254-a31eef858f95)
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/40913168/547aabd4-dc66-4a1f-8524-7566e7a52c80)

**Comment by zackabrams** [comment]
The error is accurate; the node you're using is "Apply ControlNet (Advanced)" when you should be using "Apply Advanced ControlNet 🛂🅐🅒🅝"

Also be sure to connect your model pipeline to this input

<img width="916" alt="Screenshot 2024-06-08 at 9 47 15 AM" src="https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/36209780/4fb9873d-eaff-4867-a306-cc5f1f52a073">
