### ISSUE TITLE
Help!' ControlNet' object has no attribute 'latent_format'

### ISSUE THREAD

**Issue by luozhihao1** [Kosinkadink/ComfyUI-Advanced-ControlNet#125]
The error occurred when running to the 'Load Advanced ControlNet Model' node.

Error occurred when executing ControlNetLoaderAdvanced:

'ControlNet' object has no attribute 'latent_format'

File "E:\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\nodes.py", line 41, in load_controlnet
controlnet = load_controlnet(controlnet_path, timestep_keyframe)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 562, in load_controlnet
return convert_to_advanced(control, timestep_keyframe=timestep_keyframe)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 571, in convert_to_advanced
control = ControlNetAdvanced.from_vanilla(v=control, timestep_keyframe=timestep_keyframe)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 102, in from_vanilla
global_average_pooling=v.global_average_pooling, compression_ratio=v.compression_ratio, latent_format=v.latent_format, device=v.device, load_device=v.load_device, manual_cast_dtype=v.manual_cast_dtype)

![1719591375779](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/27849858/ea1b3c7e-259a-4b3d-b49b-19f2e3eef993)

**Comment by Kosinkadink** [comment]
https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/issues/124

**Comment by sylar1128** [comment]
I have the same problem as you. How can I solve it？

**Comment by Kosinkadink** [comment]
@sylar1128 https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/issues/124

**Comment by sylar1128** [comment]
> @sylar1128 #124

Thank you very much, updating the comfyui ontology is OK
