### ISSUE TITLE
So many complex ways to manipulate the strength of controlnet, but no one has come up with a way as simple as this

### ISSUE THREAD

**Issue by RoyDingZF** [Kosinkadink/ComfyUI-Advanced-ControlNet#129]
anyone appreciate the simplicity of using curves to control weight?
![Screenshot 2024-07-08 211946](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/65075614/5514e25c-3099-4011-af0d-bb581889b546)

**Comment by Kosinkadink** [comment]
You can use curves, that's what my nodes are for. You can pass in lists of values. I just have zero interest in the JavaScript side of ComfyUI.

What you're looking for is a node that can output a list of values from a customizable graph. KJNodes pack has a node that lets you create a graph to get values out of.

**Comment by Kosinkadink** [comment]
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/7365912/b7b7550c-23c5-4aa4-8c14-b35672e2bc05)
