### ISSUE TITLE
Returning the previous latent keyframes instead of the current ones

### ISSUE THREAD

**Issue by a1lazydog** [Kosinkadink/ComfyUI-Advanced-ControlNet#13]
For the LatentKeyframeInterpolationNode:

https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/blob/6fb4ce52ffc4dd035cc72af5d397ccb39d9bcf9c/nodes.py#L391

prev_latent_keyframe is being returned instead of curr_latent_keyframe.  Thus no new latent_keyframes are actually being set by this node.

**Comment by Kosinkadink** [comment]
Thanks for the heads up, fixed!
