### ISSUE TITLE
AttributeError: 'ControlNetPlusPlus' object has no attribute 'num_control_type'

### ISSUE THREAD

**Issue by glyfspace** [Kosinkadink/ComfyUI-Advanced-ControlNet#134]
Hey! I am getting this issue when using the "Load ControlNet++ Model (Single)"

Any tips? I made sure my comfy was updated already. Thanks!

AttributeError: 'ControlNetPlusPlus' object has no attribute 'num_control_type'

**Comment by glyfspace** [comment]
```
File "/app/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control_plusplus.py", line 155, in __init__

self.control_add_embedding = ControlAddEmbeddingAdv(control_add_embed_dim, time_embed_dim, self.num_control_type, dtype=self.dtype, device=device, operations=operations)
```

this is the traceback ^^ 

thanks!

**Comment by Kosinkadink** [comment]
I piggyback of the ComfyUI controlnetobject. If that variable is not defined, it means your ComfyUI is likely not updated recently enough. I know you said you've updated ComfyUI, but I'd wager something went wrong and it failed to update.

**Comment by glyfspace** [comment]
Ok let me try updating again! Thanks!

**Comment by CGPG-Wang** [comment]
> Ok let me try updating again! Thanks!

Hello, I have the same problem. Have you solved it?

**Comment by Kosinkadink** [comment]
Update ComfyUI

**Comment by CGPG-Wang** [comment]
> Update ComfyUI
Still not working:(
The Manager page shows that the update was successful, I don't know which custom node this "ControlNetPlusPlus" belongs to, so I'll try updating it separately

**Comment by Kosinkadink** [comment]
ControlNetPlusPlus is from this repo, which is why this issue is open here. The manager might be lying. That variable is not mine, it's something that should exist on ComfyUI's controlnet code. Since your code does not have it, that means your ComfyUI is not updated.

**Comment by CGPG-Wang** [comment]
> ControlNetPlusPlus is from this repo, which is why this issue is open here. The manager might be lying. That variable is not mine, it's something that should exist on ComfyUI's controlnet code. Since your code does not have it, that means your ComfyUI is not updated.

Well、Thanks for reply dude,I have to find a solution or I won't be able to use the sdxl model, which would be a shame....

**Comment by Kosinkadink** [comment]
You just have to update ComfyUI, that's it. To confirm that your ComfyUI is outdated, paste the contents of the cldm.py file inside comfy/cldm directory and I can take a look for you.

**Comment by CGPG-Wang** [comment]
> You just have to update ComfyUI, that's it. To confirm that your ComfyUI is outdated, paste the contents of the cldm.py file inside comfy/cldm directory here and I can take a look for you.

already solved!! According to the plan you provided,Thank you very much, >3
