### ISSUE TITLE
Use 3 controlnet++ :Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by xueqing0622** [Kosinkadink/ComfyUI-Advanced-ControlNet#136]
Use 2 controlnet++ : no problem
Use 3 controlnet++ : error like this
 File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control_plusplus.py", line 196, in forward
    guided_hint = self.union_controlnet_merge(hint, control_type, emb, context)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control_plusplus.py", line 167, in union_controlnet_merge
    feat_seq += self.task_embedding[indexes[idx][0]]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by jokero3answer** [comment]
![image](https://github.com/user-attachments/assets/b39378b8-8c31-4626-86f9-77c95bd59cf1)
Me too.
[Diagnostics-1721286178.log](https://github.com/user-attachments/files/16279091/Diagnostics-1721286178.log)
@harelc

**Comment by jokero3answer** [comment]
@Kosinkadink

**Comment by Kosinkadink** [comment]
Thank you for submitting the log file, it's an issue with lowvram, I'll push out a fix soon.

**Comment by Kosinkadink** [comment]
lowvram issues for ControlNet++ should now be resolved
