### ISSUE TITLE
'ControlNet' object has no attribute 'latent_format'

### ISSUE THREAD

**Issue by mikheys** [Kosinkadink/ComfyUI-Advanced-ControlNet#140]
Good afternoon! Just updated everything (comfyUI, ComfyUI-Advanced-ControlNet) but still this error pops up(( Everything worked before.

![image](https://github.com/user-attachments/assets/57f6f94b-852b-4364-946d-dd1e7474cc21)

**Comment by Kosinkadink** [comment]
We can keep discussion about this in the main PSA thread where you posted too, hopefully you can get your ComfyUI to update. (linking for documentation's sake https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/issues/124).
