### ISSUE TITLE
（__init__.py）I have this file, but I cannot recognize importing it

### ISSUE THREAD

**Issue by cjx-ares** [Kosinkadink/ComfyUI-Advanced-ControlNet#157]
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Manager-main\\__init__.py'

**Comment by Kosinkadink** [comment]
I think your install may be messed up (and this is unrelated to Advanced-ControlNet), closing issue.
