### ISSUE TITLE
When using Reference Controlnet, clearing the model/node cache changes the result

### ISSUE THREAD

**Issue by michP247** [Kosinkadink/ComfyUI-Advanced-ControlNet#166]
Using the reference preprocessor and controlnet, I'm having trouble getting consistent results,

Here is the first image with specified seed:
![ComfyUI_00983_](https://github.com/user-attachments/assets/27efd629-4da3-4ff1-8e56-5cddd8eca9cb)

And the second image with same seed after clicking on "Free model and node cache":
![ComfyUI_00984_](https://github.com/user-attachments/assets/5d00631b-b4db-42c7-8c4d-2b6aab6cee73)

I changed absolutely no parameters as you can see if you plug those images into Comfy yourself. This bug doesn't seem to occur with other Advanced Controlnet from this plugin like when using openpose, only with the Reference nodes. No error in the console

**Comment by Kosinkadink** [comment]
What is "Free model and node cache"? Is it from another node pack, or a new ComfyUI feature?

**Comment by michP247** [comment]
> What is "Free model and node cache"? Is it from another node pack, or a new ComfyUI feature?

It's a button in teh tip right of ComfyUI as part of their new frontend. But I can clear the cache in other ways such as switching the Preprocessor to "adain+attain" then back to "adain", which gives the same issue

**Comment by Kosinkadink** [comment]
Gotcha, thanks for the heads up. I'll look into it later today

**Comment by michP247** [comment]
> What is "Free model and node cache"? Is it from another node pack, or a new ComfyUI feature?

Correction, it seems to be not new, looks like it's from the "Beta UI" that got added last month

**Comment by michP247** [comment]
Update: FreeU node seems to be the culprit. For some reason it produces tiny variations even with same seed. And when combined with the Reference nodes, these tiny changes add up to majorly change the final image somehow. This doesn't occur in A1111 or forge...maybe it's an issue for the main comfyui repo

**Comment by michP247** [comment]
> I didnt notice that you edited your comment (github does not send notifications for edits), so i put this on the back burner assuming FreeU compatibility was the issue. i'll take a look this weekend.

thanks I lowkey didnt want to spam your mail

**Comment by Kosinkadink** [comment]
I haven't had the chance to investigate this, but I know for sure it does not happen in the upcoming PR I will be merging once my ComfyUI hooks PR gets merged. I'll link the rework-modelpatcher branch to this issue so that this will automatically close after merging.

**Comment by michP247** [comment]
Yup, works fine now
