### ISSUE TITLE
Advanced controlnet is installed, but is not recognized within comfyui.

### ISSUE THREAD

**Issue by ledajjang** [Kosinkadink/ComfyUI-Advanced-ControlNet#172]
comfyui_Advanced_controlnet is installed, but is not recognized within comfyui.
How cna I solve this??

![화면 캡처 2024-09-03 114028](https://github.com/user-attachments/assets/8257dbfc-c71b-44ca-9091-959de82c9d93)
![화면 캡처 2024-09-03 114147](https://github.com/user-attachments/assets/b872026e-ee58-4fde-b0c3-7ae93c1bda78)

**Comment by Kosinkadink** [comment]
Make sure it's updated. Worst case, uninstall and reinstall. No one else is having this issue, so likely just something with your install that should be easily fixable.

**Comment by ledajjang** [comment]
> Make sure it's updated. Worst case, uninstall and reinstall. No one else is having this issue, so likely just something with your install that should be easily fixable.

I have tried the 3 ways, now. Updated, reinstall & reinstall comfyui. But this is same situation.
How can I do for this??????
Help me.
I would like to work with the photoshop......ㅠ,.ㅠ

**Comment by Kosinkadink** [comment]
Did you make sure to refresh your browser and restarting ComfuUI after installing the nodes?

**Comment by Kosinkadink** [comment]
Also, check your console for any startup errors

**Comment by Shoridosho** [comment]
did you find any solution for this? I have the same issue.
