### ISSUE TITLE
[request] workflow using advanced controlnet and ADE?

### ISSUE THREAD

**Issue by rook2pawn** [Kosinkadink/ComfyUI-Advanced-ControlNet#173]
would be helpful to see an example maybe with openpose. currently using regular controlnet openpose and would like to see how the advanced version works.

**Comment by Kosinkadink** [comment]
Its setup and identical to vanilla controlnet

**Comment by rook2pawn** [comment]
Could you provide a sample workflow? It would be of great help. i've tried with this workflow and got an error : "!!! Exception during processing !!! Without a context window, AnimateDiff model mm_sd_v15_v2.ckpt has upper limit of 32 frames, but received 54 latents".

[faulty_workflow.json](https://github.com/user-attachments/files/16845884/faulty_workflow.json)

**Comment by Kosinkadink** [comment]
Your controlnet is likely working fine, what you need to add is Context Options to your AnimateDiff nodes. There are some updated examples for AnimateDiff-Evolved that have Context Options connected: https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved?tab=readme-ov-file#txt2vid
