### ISSUE TITLE
The node is installed but is displayed in red！！

### ISSUE THREAD

**Issue by 1LucasGraham** [Kosinkadink/ComfyUI-Advanced-ControlNet#176]
![{BEA23976-CDF4-4D99-B885-58D3E8949145}](https://github.com/user-attachments/assets/77afb9b8-91e5-4dd1-888f-d0d6e3ab473d)

![{CCA5F342-8B7A-42DA-BC98-2DD238F0CB71}](https://github.com/user-attachments/assets/e04398e2-a8bf-404b-8874-2d1f760b855e)
seek help！

**Comment by Kosinkadink** [comment]
Check your console for errors

**Comment by 1LucasGraham** [comment]
![2024-09-05 180951](https://github.com/user-attachments/assets/14d7d9aa-8197-4d18-abb1-43f2cd158a98)

**Comment by Kosinkadink** [comment]
I'll be more specific: look for any startup errors with Advanced-ControlNet

**Comment by 1LucasGraham** [comment]
> I'll be more specific: look for any startup errors with Advanced-ControlNet

```
Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: /stable-diffusion

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: /stable-diffusion

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: /stable-diffusion
```

sorry. Is this error relevant?

**Comment by Kosinkadink** [comment]
Nope, it should not be relevant at all. The error you're looking for would be from code in ComfyUI-Advanced-ControlNet.

**Comment by 1LucasGraham** [comment]
> Nope, it should not be relevant at all. The error you're looking for would be from code in ComfyUI-Advanced-ControlNet.

Well, thank you

**Comment by Kosinkadink** [comment]
What I mean is, look in your console for errors from Advanced-ControlNet. What you posted is just a tiny portion of the startup logs

**Comment by 1LucasGraham** [comment]
> What I mean is, look in your console for errors from Advanced-ControlNet. What you posted is just a tiny portion of the startup logs

There are no other errors, as shown in the figure

**Comment by Kosinkadink** [comment]
That's just the early portion of the logs - can you copy and paste the entirety of your console output after booting up ComfyUI?
