### ISSUE TITLE
ACN_AdvancedControlNetApply and ControlNetLoaderAdvanced not present

### ISSUE THREAD

**Issue by EmmanuelTuloup** [Kosinkadink/ComfyUI-Advanced-ControlNet#177]
as you can see
![ACN_AdvancedControlNetApply ](https://github.com/user-attachments/assets/245ee080-c4b8-40e0-99ed-4b9ec845b40c)

**Comment by Kosinkadink** [comment]
Check your console log for errors and post them here

**Comment by EmmanuelTuloup** [comment]
seems to have no error:
-------------------------------------------
D:\PERSO\IMG\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-06 10:29:29.790144
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: D:\PERSO\IMG\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\PERSO\IMG\ComfyUI_windows_portable\ComfyUI
** Log path: D:\PERSO\IMG\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.3 seconds: D:\PERSO\IMG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

[AnimateDiffEvo] - ERROR - No motion models found. Please download one and place in: ['D:\\PERSO\\IMG\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-AnimateDiff-Evolved\\models', 'D:\\PERSO\\IMG\\ComfyUI_windows_portable\\ComfyUI\\models\\animatediff_models']
### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: 2307 [fbb7a1f1] | Released on '2024-06-29'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\PERSO\IMG\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
D:\PERSO\IMG\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
FizzleDorf Custom Nodes: Loaded
FETCH DATA from: D:\PERSO\IMG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: D:\PERSO\IMG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: D:\PERSO\IMG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
-------------------------------------------

but a have loaded an (too) old graph json, and have the message in the browser 
"When loading the graph, the following node types were not found: 

    ControlNetLoaderAdvanced
    ACN_AdvancedControlNetApply

Nodes that have failed to load will show as red on the graph."

**Comment by EmmanuelTuloup** [comment]
[2024-09-06 10:13] Cannot import D:\PERSO\IMG\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet module for custom nodes: cannot import name 'StrengthType' from 'comfy.controlnet' (D:\PERSO\IMG\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py)

**Comment by Kosinkadink** [comment]
Your ComfyUI is too outdated - update ComfyUI and your error will go away

**Comment by EmmanuelTuloup** [comment]
thanks a lot !

**Comment by ploughboy27** [comment]
I updated Comfy and started getting this error!

**Comment by Kosinkadink** [comment]
It means you have a startup error. You can see the details if you look at your startup log (and I think manager allows you to view import error details for specific node packs now), but most likely you just need to update your Advanced-ControlNet nodes. You updated ComfyUI (and it's likely been a while since your last update), so you'll need to update custom nodes as well.
