### ISSUE TITLE
Receiving No such file or directory error- ComfyUI-tbox

### ISSUE THREAD

**Issue by Mythomyth** [Kosinkadink/ComfyUI-Advanced-ControlNet#179]
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Comfy\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-tbox\\..\\..\\models\\annotator\\hr16\\DWPose-TorchScript-BatchSize5\\.cache\\huggingface\\download\\dw-ll_ucoco_384_bs5.torchscript.pt.d86a0b2b59fddc0901a7076e9f59c9f8602602133ed72511c693fd11eea23d91.incomplete'

![image](https://github.com/user-attachments/assets/b5c1de04-27da-4b2e-a7ef-07715807fb51)

**Comment by Kosinkadink** [comment]
This is an error reported by ComfyUI-tbox, not ComfyUI-Advanced-ControlNet, closing.
