### ISSUE TITLE
Issues with sparse_method: ACN_AdvancedControlNetApply node.

### ISSUE THREAD

**Issue by ArnauTasies** [Kosinkadink/ComfyUI-Advanced-ControlNet#180]
Hello, first of all thing for your amazing work.

Since last ComfyUI and Advanced ControlNet updates  I ve got an error with workflows two months old.
The issue seems to appear when the workflow reaches the Apply Advance Controlnet node
Any help would be appreciated.
Thanks for your time
Here is the message I get.

got prompt
Failed to validate prompt for output 281:
* ACN_SparseCtrlLoaderAdvanced 965:
  - Return type mismatch between linked nodes: sparse_method, STRING != SPARSE_METHOD
Output will be ignored
Failed to validate prompt for output 207:
Output will be ignored
Failed to validate prompt for output 805:
Output will be ignored
WARNING: DreamInputInt.IS_CHANGED() got an unexpected keyword argument 'value'
WARNING: DreamImageBrightness.IS_CHANGED() got an unexpected keyword argument 'factor'

**Comment by Kosinkadink** [comment]
Can you provide a screenshot of the connection between the nodes? Advanced-ControlNet is working fine, if an external node is trying to create an input that connects to the Sparse node, that external node may need an update on their end.

**Comment by ArnauTasies** [comment]
Woooow, man! Thanks your feedback!!!!
As you pointed, the problem comes from a previous node: Banodoco Steerable Motion Node (the Batch Creative Interpolation node). Just building a new workflow (no Steerable motion involved) solves the issue.
Hopefully Banodoco will upgrade their nodes...
Thank you very much for your work and your feeback!! Have a good one!!! <3

**Comment by LorisTecnology** [comment]
getting the same error 
* ACN_SparseCtrlLoaderAdvanced 467:
  - Return type mismatch between linked nodes: sparse_method, STRING != SPARSE_METHOD


I guess is up to Bandocoo to fix it

**Comment by ZYOhub** [comment]
May I ask how you solved it? I am a beginner. Using someone else's workflow and encountering the same problem as you, what nodes can be replaced or how can they be fixed? thank you!

**Comment by ZYOhub** [comment]
I added a SparseCtrl Index Method between Keyframe_positions and sparse_math. succeed!
