### ISSUE TITLE
What are the functions of these interfaces

### ISSUE THREAD

**Issue by wencxxxxxx** [Kosinkadink/ComfyUI-Advanced-ControlNet#183]
![屏幕截图 2024-09-26 183511](https://github.com/user-attachments/assets/949ed7b1-6bef-4c68-a758-fe389f1c232c)

**Comment by Kosinkadink** [comment]
vae_optional is needed for some controlnet types. model_optional does nothing, it was something that was needed in the past. In an upcoming update, the version of the node that contains model_optional input/output will be hidden, and replaced with a version that excludes it.
https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/pull/198
