### ISSUE TITLE
KSampler error when I try to modify uncond_multiplier

### ISSUE THREAD

**Issue by adanmq** [Kosinkadink/ComfyUI-Advanced-ControlNet#185]
Hi!
Thanks for this amazing set of nodes. Almost everything is working flawlessly for me, but when I try to modify uncond_multiplier to get the same results as CN, it seems more important to use Soft Weights or any other node. However, I get a KSampler error: 'int' object has no attribute 'cond_or_uncond'.

I´m using Apply Adv CN, Load Adv CN Model and connecting CN_WEIGHTS to the Weights_override input. 
![image](https://github.com/user-attachments/assets/c80e8a38-7ff5-4d31-bc28-fd35bcd8d8b9)

I've tried several different things but haven’t found a solution. I would really appreciate some help.

Best regards!

**Comment by Kosinkadink** [comment]
The current uncond_multiplier implementation is very hacky and may break depending on what else is connected in the workflow.

In an upcoming ComfyUI update I'm working on, I will be able to have a much cleaner implementation that will never break. I'll update this issue when that goes live.

**Comment by adanmq** [comment]
Fantastic! 
Thank you so much for taking the time to respond. I'll be on the lookout for the next update. Thanks again!

**Comment by Kosinkadink** [comment]
When my upcoming ACN PR gets merged after my ComfyUI PR (hopefully around US Thanksgiving, it's out of my hands lol), the fix for this will be included in there: https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/pull/198
