### ISSUE TITLE
 FLOAT != VAE

### ISSUE THREAD

**Issue by zmczmc123654** [Kosinkadink/ComfyUI-Advanced-ControlNet#187]
Failed to validate prompt for output 1676:
* ScaledSoftControlNetWeights 494:
  - Return type mismatch between linked nodes: cn_extras, FLOAT != CN_WEIGHTS_EXTRAS
* ConditioningMultiCombine 1491:
  - Value not in list: operation: 'None' not in ['combine', 'concat']
* ACN_AdvancedControlNetApply 21:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
* ACN_AdvancedControlNetApply 355:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
* ACN_AdvancedControlNetApply 23:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
Output will be ignored
Failed to validate prompt for output 1507:
Output will be ignored
Failed to validate prompt for output 2016:
* ACN_AdvancedControlNetApply 1532:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
* ACN_AdvancedControlNetApply 1505:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
Output will be ignored
Failed to validate prompt for output 218:
Output will be ignored
Failed to validate prompt for output 629:
Output will be ignored
Failed to validate prompt for output 217:
Output will be ignored
Failed to validate prompt for output 2037:
Output will be ignored
Failed to validate prompt for output 1703:
Output will be ignored
Failed to validate prompt for output 2024:
Output will be ignored
Failed to validate prompt for output 630:
Output will be ignored
WARNING: [Errno 2] No such file or directory: 'D:\\SDAI\\ComfyUI-aki-v1.3\\input\\31232131231.jpg'
Prompt executed in 0.53 seconds
got prompt
Failed to validate prompt for output 1676:
* ScaledSoftControlNetWeights 494:
  - Return type mismatch between linked nodes: cn_extras, FLOAT != CN_WEIGHTS_EXTRAS
* ConditioningMultiCombine 1491:
  - Value not in list: operation: 'None' not in ['combine', 'concat']
* ACN_AdvancedControlNetApply 21:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
* ACN_AdvancedControlNetApply 355:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
* ACN_AdvancedControlNetApply 23:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
Output will be ignored
Failed to validate prompt for output 1507:
Output will be ignored
Failed to validate prompt for output 2016:
* ACN_AdvancedControlNetApply 1532:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
* ACN_AdvancedControlNetApply 1505:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
Output will be ignored
Failed to validate prompt for output 218:
Output will be ignored
Failed to validate prompt for output 629:
Output will be ignored
Failed to validate prompt for output 217:
Output will be ignored
Failed to validate prompt for output 2037:
Output will be ignored
Failed to validate prompt for output 1703:
Output will be ignored
Failed to validate prompt for output 2024:
Output will be ignored
Failed to validate prompt for output 630:
Output will be ignored
WARNING: [Errno 2] No such file or directory: 'D:\\SDAI\\ComfyUI-aki-v1.3\\input\\31232131231.jpg'
Prompt executed in 0.51 seconds
got prompt
Failed to validate prompt for output 1676:
* ScaledSoftControlNetWeights 494:
  - Return type mismatch between linked nodes: cn_extras, FLOAT != CN_WEIGHTS_EXTRAS
* ConditioningMultiCombine 1491:
  - Value not in list: operation: 'None' not in ['combine', 'concat']
* ACN_AdvancedControlNetApply 21:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
* ACN_AdvancedControlNetApply 355:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
* ACN_AdvancedControlNetApply 23:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
Output will be ignored
Failed to validate prompt for output 1507:
Output will be ignored
Failed to validate prompt for output 2016:
* ACN_AdvancedControlNetApply 1532:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
* ACN_AdvancedControlNetApply 1505:
  - Return type mismatch between linked nodes: vae_optional, FLOAT != VAE
Output will be ignored
Failed to validate prompt for output 218:
Output will be ignored
Failed to validate prompt for output 629:
Output will be ignored
Failed to validate prompt for output 217:
Output will be ignored
Failed to validate prompt for output 2037:
Output will be ignored
Failed to validate prompt for output 1703:
Output will be ignored
Failed to validate prompt for output 2024:
Output will be ignored
Failed to validate prompt for output 630:
Output will be ignored

**Comment by Kosinkadink** [comment]
Cannot reproduce your issue, if you are loading a very old workflow, make sure to refresh the page before running it.

**Comment by zmczmc123654** [comment]
> Cannot reproduce your issue, if you are loading a very old workflow, make sure to refresh the page before running it.
ACN_AdvancedControlNetApply
'ControlNet' object has no attribute 'device'


# ComfyUI Error Report
## Error Details
- **Node Type:** ACN_AdvancedControlNetApply
- **Exception Type:** AttributeError
- **Exception Message:** 'ControlNet' object has no attribute 'device'
## Stack Trace
```
  File "D:\SDAI\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\SDAI\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\SDAI\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\SDAI\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\SDAI\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\nodes.py", line 144, in apply_controlnet
    c_net = convert_to_advanced(control_net.copy()).set_cond_hint(control_hint, strength, (start_percent, end_percent), vae_optional)

  File "D:\SDAI\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 515, in convert_to_advanced
    control = ControlNetAdvanced.from_vanilla(v=control, timestep_keyframe=timestep_keyframe)

  File "D:\SDAI\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\control.py", line 129, in from_vanilla
    global_average_pooling=v.global_average_pooling, compression_ratio=v.compression_ratio, latent_format=v.latent_format, device=v.device, load_device=v.load_device,

i update the nodes,now came up with other issuse   above ,i don't konw haow to deal with that,

**Comment by Kosinkadink** [comment]
Update your Advanced-ControlNet nodes and your device error will go away: https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/issues/191

**Comment by zmczmc123654** [comment]
it work thanks you

**Comment by zmczmc123654** [comment]
> Update your Advanced-ControlNet nodes and your device error will go away: #191

it work thanks you,
