### ISSUE TITLE
Node Error After Updating ComfyUI Today

### ISSUE THREAD

**Issue by shmilyfuu** [Kosinkadink/ComfyUI-Advanced-ControlNet#189]
After updating ComfyUI today, the node encountered an error and can no longer run properly. However, everything was working fine before today's update. This is a very simple workflow, and I am not sure what went wrong. Below is the error log.
[workflow.json](https://github.com/user-attachments/files/17500465/workflow.json)
![WX20241024-110642@2x](https://github.com/user-attachments/assets/a9f9a9b3-aa49-4ae0-a48b-8a9ec31d6f7d)

**Comment by Kosinkadink** [comment]
Luckily for you, just a few minutes ago I pushed an update for Advanced-ControlNet to make it work with latest comfyui (and breaks for all previous versions of ComfyUI).

If you update Advanced-ControlNet now, your error should go away.

**Comment by shmilyfuu** [comment]
Wow, that's great! Thank you so much for your response. I'll give it a try right away.

**Comment by shmilyfuu** [comment]
Just as you mentioned, it’s working normally now! Thank you for the update.

**Comment by Kosinkadink** [comment]
For sake of clarity, linking the new PSA issue about needing to update ACN
https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/issues/189
