### ISSUE TITLE
[Feature Request] CtrLoRA support!

### ISSUE THREAD

**Issue by toyxyz** [Kosinkadink/ComfyUI-Advanced-ControlNet#193]
https://github.com/xyfJASON/ctrlora

Similar to Lora, CtrLora can create a ControlNet Lora in a short time (1 hour) with a small number of datasets (1000).

It works very well in practice and is easy to train. Here is a test I did.

![image](https://github.com/user-attachments/assets/7fc2fc70-765c-4c1b-ab96-e92de7a6a72a)
![image](https://github.com/user-attachments/assets/9b94ecd3-4a7c-4678-bfc0-1ace1dfd4359)
![image](https://github.com/user-attachments/assets/5b6860bf-2844-48d5-9f75-257bb7839a9e)

**Comment by Kosinkadink** [comment]
I should have time to implement it in November, currently working on ModelPatcher changes for core ComfyUI.

**Comment by toyxyz** [comment]
https://github.com/zmwv823/ComfyUI_Ctrlora

**Comment by Kosinkadink** [comment]
CtrLoRA support is now available on the rework-modelpatcher branch; when my ComfyUI PR gets merged, the corresponding ACN PR will get merged as well that will bring it to the main branch too.
https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/pull/198
