### ISSUE TITLE
Today fresh install do not work : ACN_ScaledSoftControlNetWeights  'int' object has no attribute 'copy'

### ISSUE THREAD

**Issue by P1LeFR** [Kosinkadink/ComfyUI-Advanced-ControlNet#210]
I assume due to all changes and updates things are not fine tuned.
As the result ACN node do not work anymore. To check I create a today a fresh install. But failed to run my workflow.

> ACN_ScaledSoftControlNetWeights
> 
> 'int' object has no attribute 'copy'
> 
> 
> # ComfyUI Error Report
> ## Error Details
> - **Node ID:** 13
> - **Node Type:** ACN_ScaledSoftControlNetWeights
> - **Exception Type:** AttributeError
> - **Exception Message:** 'int' object has no attribute 'copy'
> ## Stack Trace
> ```
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
>     process_inputs(input_dict, i)
> 
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\nodes_weight.py", line 96, in load_weights
>     weights = ControlWeights.universal(base_multiplier=base_multiplier, uncond_multiplier=uncond_multiplier, extras=cn_extras)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 122, in universal
>     return cls(ControlWeightType.UNIVERSAL, base_multiplier=base_multiplier, uncond_multiplier=uncond_multiplier, disable_applied_to=True, extras=extras)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 83, in __init__
>     self.extras = extras.copy()
>                   ^^^^^^^^^^^
> 
> ```
> ## System Information
> - **ComfyUI Version:** v0.3.7
> - **Arguments:** ComfyUI\main.py --windows-standalone-build
> - **OS:** nt
> - **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
> - **Embedded Python:** true
> - **PyTorch Version:** 2.5.1+cu124
> ## Devices
> ...
> 
> 2024-12-08T20:33:42.358355 - Starting server
> 
> 2024-12-08T20:33:42.358355 - To see the GUI go to: http://127.0.0.1:8188
> 2024-12-08T20:33:42.406910 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-12-08T20:33:42.406910 - 
> 2024-12-08T20:33:42.543050 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-12-08T20:33:42.543050 - 
> 2024-12-08T20:33:43.204556 - FETCH DATA from: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2024-12-08T20:33:43.204556 - 2024-12-08T20:33:43.207556 -  [DONE]2024-12-08T20:33:43.207556 - 
> 2024-12-08T20:33:43.683319 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
>                   Your current root directory is: E:\ComfyUI_windows_portable\ComfyUI
>             2024-12-08T20:33:43.683319 - 
> 2024-12-08T20:33:43.683319 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
>                   Your current root directory is: E:\ComfyUI_windows_portable\ComfyUI
>             2024-12-08T20:33:43.684319 - 
> 2024-12-08T20:33:43.684319 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
>                   Your current root directory is: E:\ComfyUI_windows_portable\ComfyUI
>             2024-12-08T20:33:43.684319 - 
> 2024-12-08T20:33:43.684319 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
>                   Your current root directory is: E:\ComfyUI_windows_portable\ComfyUI
>             2024-12-08T20:33:43.684319 - 
> 2024-12-08T20:33:43.684319 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
>                   Your current root directory is: E:\ComfyUI_windows_portable\ComfyUI
>             2024-12-08T20:33:43.684319 - 
> 2024-12-08T20:33:43.684319 - Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
>                   Your current root directory is: E:\ComfyUI_windows_portable\ComfyUI
>             2024-12-08T20:33:43.684319 - 
> 2024-12-08T20:33:47.561137 - got prompt
> 2024-12-08T20:33:47.574645 - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
> 2024-12-08T20:33:47.790533 - Using pytorch attention in VAE
> 2024-12-08T20:33:47.792537 - Using pytorch attention in VAE
> 2024-12-08T20:33:49.582317 - clip missing: ['text_projection.weight']
> 2024-12-08T20:33:49.999586 - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
> 2024-12-08T20:33:50.005530 - model_type FLUX
> 2024-12-08T20:33:55.294349 - Requested to load FluxClipModel_
> 2024-12-08T20:33:56.205395 - loaded completely 9.5367431640625e+25 4777.53759765625 True
> 2024-12-08T20:34:03.576233 - Requested to load FluxClipModel_
> 2024-12-08T20:34:04.507993 - loaded completely 9.5367431640625e+25 4777.53759765625 True
> 2024-12-08T20:34:04.633318 - !!! Exception during processing !!! 'int' object has no attribute 'copy'
> 2024-12-08T20:34:04.642107 - Traceback (most recent call last):
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\nodes_weight.py", line 96, in load_weights
>     weights = ControlWeights.universal(base_multiplier=base_multiplier, uncond_multiplier=uncond_multiplier, extras=cn_extras)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 122, in universal
>     return cls(ControlWeightType.UNIVERSAL, base_multiplier=base_multiplier, uncond_multiplier=uncond_multiplier, disable_applied_to=True, extras=extras)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 83, in __init__
>     self.extras = extras.copy()
>                   ^^^^^^^^^^^
> AttributeError: 'int' object has no attribute 'copy'
> 
> 2024-12-08T20:34:04.643108 - Prompt executed in 17.08 seconds
> 2024-12-08T20:34:09.639304 - got prompt
> 2024-12-08T20:34:09.660510 - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
> 2024-12-08T20:34:09.762452 - !!! Exception during processing !!! 'int' object has no attribute 'copy'
> 2024-12-08T20:34:09.763452 - Traceback (most recent call last):
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\nodes_weight.py", line 96, in load_weights
>     weights = ControlWeights.universal(base_multiplier=base_multiplier, uncond_multiplier=uncond_multiplier, extras=cn_extras)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 122, in universal
>     return cls(ControlWeightType.UNIVERSAL, base_multiplier=base_multiplier, uncond_multiplier=uncond_multiplier, disable_applied_to=True, extras=extras)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 83, in __init__
>     self.extras = extras.copy()
>                   ^^^^^^^^^^^
> AttributeError: 'int' object has no attribute 'copy'
> 
> 2024-12-08T20:34:09.764835 - Prompt executed in 0.11 seconds
> 2024-12-08T20:35:57.448457 - got prompt
> 2024-12-08T20:35:57.461052 - WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'
> 2024-12-08T20:35:57.506453 - !!! Exception during processing !!! 'int' object has no attribute 'copy'
> 2024-12-08T20:35:57.507453 - Traceback (most recent call last):
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
>     output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
>     return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
>     process_inputs(input_dict, i)
>   File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
>     results.append(getattr(obj, func)(**inputs))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\nodes_weight.py", line 96, in load_weights
>     weights = ControlWeights.universal(base_multiplier=base_multiplier, uncond_multiplier=uncond_multiplier, extras=cn_extras)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 122, in universal
>     return cls(ControlWeightType.UNIVERSAL, base_multiplier=base_multiplier, uncond_multiplier=uncond_multiplier, disable_applied_to=True, extras=extras)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 83, in __init__
>     self.extras = extras.copy()
>                   ^^^^^^^^^^^
> AttributeError: 'int' object has no attribute 'copy'

**Comment by Kosinkadink** [comment]
Can you take a screenshot of the ACN nodes setup in your workflow? It will let me try to reproduce the issue.

**Comment by P1LeFR** [comment]
Sure thank you for such a prompt answer ! [Partial Flow view](https://github.com/user-attachments/assets/405a362d-0d1a-4251-a8e6-2cefac6eb529)
The original workflow is the one of zyd232 
https://civitai.com/models/899863/loop-upscale-automated-upscale-workflow-for-different-scenarios

**Comment by Kosinkadink** [comment]
Looking at the original workflow and yours, you've accidentally plugged in the output of that "base_shift of else node", which outputs an int, into 'cn_extras', which is not an int, causing the issue. Unplug it and everything will be fine.

**Comment by P1LeFR** [comment]
> Looking at the original workflow and yours, you've accidentally plugged in the output of that "base_shift if else node", which outputs an int, into 'cn_extras', which is not an int, causing the issue. Unplug it and everything will be fine.

Thank you so much! Yes problem solved.
This connector was already connected by mistake before and do not generate problems.

You are making a wonderful work, very appreciated.
