### ISSUE TITLE
Is this the correct way to apply conditioning ONLY for the first n frames?

### ISSUE THREAD

**Issue by Jaxkr** [Kosinkadink/ComfyUI-Advanced-ControlNet#25]
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/1147244/117a40b0-7e76-457e-be04-518b91b498a3)

In my understanding, this will apply to frames 0 (`batch_index_from`) through 15 (`batch_index_to_excl - 1`). Since the strength goes from 1 to 0, it will immediately stop applying and have no influence on frame 17.

The one thing I don't understand is what exactly `start_percent` means. If I set it to 1 it applies through my whole sequence.

**Comment by Kosinkadink** [comment]
Hey, I recently pushed a major overhaul of these nodes, and the start_percent on the Timestep Keyframes does something now! Check out the new README for info.
