### ISSUE TITLE
Apply Advanced ControlNet doesn't seem to be working.

### ISSUE THREAD

**Issue by toyxyz** [Kosinkadink/ComfyUI-Advanced-ControlNet#28]
Apply Advanced ControlNet doesn't seem to be working. 

It was working fine a few hours ago, but I updated ComfyUI and got that issue. 

![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/8006000/684d569a-9af9-4388-9511-c97d0ceb90e3)

**Comment by Kosinkadink** [comment]
Looks like the new ComfyUI update changed some things, I'll get a fix out soon!

**Comment by taconugget** [comment]
Im seeing the same issues as well @Kosinkadink Thank you! Happened after todays update.

**Comment by taconugget** [comment]
New merge fixed it thanks @Kosinkadink THANK YOU!

**Comment by Kosinkadink** [comment]
Oops, yeah I forgot to write a comment here once I uploaded the fix, Apply Advanced ControlNet node now works as intended with new Comfy update (but will not longer work properly with older ComfyUI).

**Comment by toyxyz** [comment]
> Oops, yeah I forgot to write a comment here once I uploaded the fix, Apply Advanced ControlNet node now works as intended with new Comfy update (but will not longer work properly with older ComfyUI).

It works well now! thanks!
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/8006000/c788fe43-c458-4553-b15c-97655a635d55)
