### ISSUE TITLE
Fizznodes for driving scheduled strength instead of hard programming the keyframes

### ISSUE THREAD

**Issue by FizzleDorf** [Kosinkadink/ComfyUI-Advanced-ControlNet#3]
https://github.com/FizzleDorf/ComfyUI_FizzNodes
These nodes are meant to schedule any int or float input and can even be audio synced. You don't really have to worry about keeping track of keyframes at all. Instead, pr the missing options into comfyui so they won't have to go looking for a more proper implementation.

**Comment by Kosinkadink** [comment]
Just added the Latent Keyframe Batched Group node, that can accept input from BatchValueSchedule for strengths.
