### ISSUE TITLE
AttributeError: 'ControlNetAdvanced' object has no attribute 'verify_all_weights'

### ISSUE THREAD

**Issue by Yaeph** [Kosinkadink/ComfyUI-Advanced-ControlNet#35]
https://i.imgur.com/u8MXO03.png

https://i.imgur.com/lOnb19Y.png

https://i.imgur.com/InFSyO2.png

This error appears on Apply Advanced Controlnet node. 
Reinstalled ComfyUi, reinstalled nodes - 
https://i.imgur.com/UH9AD0b.png 
https://i.imgur.com/GtX9Yrw.png

The workflow works for other people, but not for me.

[inpainting-workflow.json](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/files/13623959/inpainting-workflow.json)

**Comment by Kosinkadink** [comment]
Can you send a screenshot of the entirety of your custom_nodes folder in ComfyUI? The error you get should not be possible, but there's a chance you accidentally have two ComfyUI-Advanced-ControlNet folders, one of which is updated to the latest version  and one of which is not, causing a mix of old and new code trying to run together.

This can happen if you decided to copy the folder to keep at is a "backup", but didn't disable it or didn't move it out of the custom_nodes directory. To keep the python and the ComfyUI-Manager from getting confused, never keep two versions of the same nodes at the same time in the custom_nodes folder (assuming this is actually the cause of your issue).

If you do see two Advanced-ControlNet folders in your ComfyUI/custom_nodes directory, delete the one that's on an older commit; if you don't know how to tell which is which, delete both and then reinstall Advanced-ControlNet.

**Comment by Kosinkadink** [comment]
Also, what version of python are you running?

**Comment by Yaeph** [comment]
> Can you send a screenshot of the entirety of your custom_nodes folder in ComfyUI? The error you get should not be possible, but there's a chance you accidentally have two ComfyUI-Advanced-ControlNet folders, one of which is updated to the latest version and one of which is not, causing a mix of old and new code trying to run together.
> 
> This can happen if you decided to copy the folder to keep at is a "backup", but didn't disable it or didn't move it out of the custom_nodes directory. To keep the python and the ComfyUI-Manager from getting confused, never keep two versions of the same nodes at the same time in the custom_nodes folder (assuming this is actually the cause of your issue).
> 
> If you do see two Advanced-ControlNet folders in your ComfyUI/custom_nodes directory, delete the one that's on an older commit; if you don't know how to tell which is which, delete both and then reinstall Advanced-ControlNet.

you are right, there was another folder of Advanced-Controlnet-main from some other workflow, deleting it solved the issue, thanks a lot!
