### ISSUE TITLE
Error occurred when executing KSampler:  Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)

### ISSUE THREAD

**Issue by dchatel** [Kosinkadink/ComfyUI-Advanced-ControlNet#36]
To reproduce you just need to connect an adv controlnet apply or adv controlnet loader.
For example this will work:
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/1372055/4322b9bc-2b09-402a-95fc-cd31e2b92b1f)
and this won't:
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/1372055/5d3323ae-f9e2-4960-b42f-cd48d2d8e4a5)

**Comment by Kosinkadink** [comment]
Looks like there was an update in ComfyUI that broke something, I'll investigate and hopefully push a fix up within the hour.

**Comment by Kosinkadink** [comment]
I've pushed an update now that should make it work with the newest version of ComfyUI (and is not backwards compatible) - let me know if it works on your end!

**Comment by dchatel** [comment]
That works. Thanks a lot!
