### ISSUE TITLE
Easy in. Easy out. From strength

### ISSUE THREAD

**Issue by bihailantian655** [Kosinkadink/ComfyUI-Advanced-ControlNet#40]
How. To.  Set.  Easy in. Easy out.  strength.

**Comment by Kosinkadink** [comment]
https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet?tab=readme-ov-file#latent-keyframe-interpolation

**Comment by bihailantian655** [comment]
## **Sorry, I didn't make the question clear**

1. easyin should go up from 0 to 1, 
2. easyout should go down from 1 to 0, 
3. easyin  easyout    I think should go up from 0 to 1 and then go down from 1 to 0.    

so i am confused  How. To. Set. Easy in. Easy out. strength.             strength.   from      strength.  to       1-0  or 0-1   





![{1981004E-9243-4f19-AC11-BFEEF5BE698A}](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/35267721/998d2f19-cf66-4a5b-be85-447a8632ebf2)
