### ISSUE TITLE
LoadImagesFromDirectory nodes don't works after Merge PR #42 from Kosinkadink/develop - SparseCtrl support

### ISSUE THREAD

**Issue by gtbloody** [Kosinkadink/ComfyUI-Advanced-ControlNet#43]
control/nodes.py delete the codes about "LoadImagesFromDirectory", 
then the older workflows will show red error:
When loading the graph, the following node types were not found:
LoadImagesFromDirectory
is it a bug ？
<img width="829" alt="image" src="https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/130019359/7d10022a-6766-4021-a040-84b3b670d3df">

<img width="678" alt="image" src="https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/130019359/a5bf95b4-cd62-4edc-9d1c-798cac969b58">

**Comment by gtbloody** [comment]
I rolled back to the December 13 version that solved the problem.

**Comment by Kosinkadink** [comment]
I deleted that node as it's deprecated and didn't think anyone was using it. You can use the load Images node from VideoHelperSuite instead

**Comment by Kosinkadink** [comment]
I might add it back just to save me from having to explain why I removed it, but I recommend not using it in the first place - I marked it as deprecated a few months ago because I will not be supporting it anymore in this repo, all the image loading stuff is in my VideoHelperSuite repo.

**Comment by Kosinkadink** [comment]
The node that will behave identical to this one is "Load Images (Path)" in VideoHelperSuite, to be exact.

**Comment by kevingre** [comment]
I would love to have it dropped it back in - that or update the VideoHelperSuite version to handle inputs to its values.  The ability to set values via inputs allow you to change the value in one spot if it's used in multiple places - the LoadImagesFromDirectory from this repo did that and I'm guessing there are a good number of workflows that rely on that type of capability.  

Totally understand only having it in one Repo to maintain, but would be great if it had the same functionality :)

**Comment by Kosinkadink** [comment]
I'm about to blow your mind - you can set any nodes' values as inputs. Just right click on a node, and select "convert widget to input". The deprecated node here has nothing special about it - the workflow you loaded must have had the person who created it already right click and convert a specific widget to an input. If you were to put in the deprecated image load node in you'd see the values start off as widgets as well.

**Comment by kevingre** [comment]
OMG!!! You did exactly that!! lol. As I was writing this (as an obvious newbie to ComfyUI), I was thinking - watch, I bet there's a way to set these via an input that I had no idea about - lol.  Thanks SO much for everything you do :). Will switch over to the VideoHelperSuite version.  Thanks again!!

**Comment by Kosinkadink** [comment]
Np! I'll also add back the deprecated node to at least not break previous workflows.

**Comment by Kosinkadink** [comment]
I added the deprecated node back, so I'll close the issue now.
