### ISSUE TITLE
SparseCtrl multiple keyframes input support 

### ISSUE THREAD

**Issue by Emersonksc** [Kosinkadink/ComfyUI-Advanced-ControlNet#46]
How to implement the Keyframe Interpolation or video Interpolation mentioned [here](https://guoyww.github.io/projects/SparseCtrl/).
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/48752001/69b8ea9f-f7fc-4540-b9cf-e30ed626fe6d)
I have played around with your tool for a while, but still not figured out how to do it, what all I could do is a single frame workflow
[Image removed by Kosinkadink lol]

**Comment by Kosinkadink** [comment]
My brother in Christ, please don't post bare breasts on my GitHub page lmao, I'm not trying to get got by GitHub staff.

To answer your question, batch more than one image and use it as input. Please edit your post to make the image less risqué first though.

**Comment by Kosinkadink** [comment]
Note: I apparently can edit people's posts, so I edited yours to remove the image

**Comment by Emersonksc** [comment]
I apologize for the inconvenient, I'll change it asap

**Comment by Emersonksc** [comment]
That's okay
