### ISSUE TITLE
Error occurred when executing ControlNetApplyAdvanced:

### ISSUE THREAD

**Issue by Esknder12** [Kosinkadink/ComfyUI-Advanced-ControlNet#48]
![Screenshot 2024-01-02 160047](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/155451315/be308cc1-45e7-4ece-b566-1e2150f8d60a)
Error occurred when executing ControlNetApplyAdvanced:

'NoneType' object has no attribute 'copy'

File "D:\comfy ui\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\comfy ui\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\comfy ui\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "D:\comfy ui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 750, in apply_controlnet
c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent))
^^^^^^^^^^^^^^^^
comfyui error
is thair any one knows about this error Tell me how to fix

**Comment by Esknder12** [comment]
![Uploading Screenshot 2024-01-02 161246.png…]()

**Comment by Kosinkadink** [comment]
Your second screenshot is not working, but Apply ControlNet node saying the controlnet object is None suggests whatever controlnet you were loading did not load. What ControlNet were you attempting to load?

**Comment by Esknder12** [comment]
![Uploading Screenshot 2024-01-02 161246.png…]()

**Comment by Sankgreall** [comment]
Am having the same issue here, suspect there is a actually bug.

The specific error I get in the console is: `error checkpoint does not contain controlnet or t2i adapter data /content/gdrive/MyDrive/ComfyUI/models/controlnet/ip-adapter-plus-face_sd15.safetensors`

However, I am using SD 1.5 models and my checkpoint is RealisticVision, which is based on SD 1.5.

Exact same models and implementation are working on AUTOMATIC 1111 (same model download script running in both locations).

**Comment by Kosinkadink** [comment]
To use IP adapter, you need to use the IPAdapter-plus nodes, which aren't maintained by me.

**Comment by krahnikblis** [comment]
i'm getting the same error "'NoneType' object has no attribute 'copy'" when trying to use the t2i-adapter "style" model. or when trying to use the stability control-lora revision model... both variants had the same use case intent - use a reference image to get a consistent character/style to the animatediff process...

**Comment by Kosinkadink** [comment]
@krahnikblis  Can you link the exact models that give you that error? That suggests ComfyUI is unable to load them, meaning they would need extra code to be handled, or something updated that I don't know about. Can you also paste your full error stack from the console?

I also just pushed an update with a fix ComfyUI implemented yesterday for a T2IAdapter-related bug. Should not effect your issue one way or the other, but can you update Advanced-ControlNet before trying again and getting the error stack from the console?

**Comment by Kosinkadink** [comment]
I'm going to assume this is no longer an issue, closing.

**Comment by Iemand005** [comment]
I'm having the same issue, models used from here: https://huggingface.co/lllyasviel/sd_control_collection/tree/main

ComfyUI\nodes.py", line 851, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
    AttributeError: 'NoneType' object has no attribute 'copy'
    
 it's not loading the model and I don't see a reason why, unless SDXL controlnet models are not supported?

**Comment by Kosinkadink** [comment]
It should work and it works on my end. Your error suggests your controlnet didn't load properly in the first place and returned None instead. Try to redownload the model, and make sure it's selected in the drop-down after refreshing the workflow; if you drag the workflow that has an unrecognized model name, it will not tell you anything is wrong.

Can you post the full error stack AND the logs from the moment you pressed Queue?
