### ISSUE TITLE
KeyError: 'control_model.out.2.weight' following ComfyUI 2024-01-02 update

### ISSUE THREAD

**Issue by andrewlabx** [Kosinkadink/ComfyUI-Advanced-ControlNet#49]
Hi,
First of all, happy new year and all the best.

I would need your help.

Following the latest ComfyUI update, I get the attached error when using controlnet nodes in workflows that worked just fine before the update.
Whatever the adapter I load, the message is the same.

Versions :
ComfyUI: 1872[8e2c99] - (2024-01-02)
Manager: V1.13.7

I also updated ComfyUI-Advanced-ControlNet custom node but that doesn't change anything.

Has anyone a clue of what could be the issue?
Thank you

![control_model_out_2_weight_error_20240103](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/155528764/64f35499-2153-46b4-872d-37391d9b9893)

**Comment by Kosinkadink** [comment]
Hey, can you try using the Load Advanced Control net node from this repo? The one you're using there is the default ComfyUI one. I don't think that will fix your problem as I reuse the comfy code for normal ControlNet loading, but I want to see what happens.

Can you also provide a screenshot of your workflow, as well as the output from your console? The error implies whatever controlnet model you're trying to load  does not have the expected key.

**Comment by andrewlabx** [comment]
Thanks for your quick response.
I removed the node and cloned the one from the repo but as you anticipated, I get the same message.

You'll also find the workflow below (and its json file)

![test_1_workflow](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/155528764/7a2bcd93-55c2-45ca-8180-096fd6dbd8aa)


![control_model_out_2_weight_error_20240103_2](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/155528764/5784e8e5-48fe-4361-9683-1a8f4a2ffcd3)

[test_1.json](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/files/13817567/test_1.json)

**Comment by Kosinkadink** [comment]
Looks like it was a temporary issue with ComfyUI: https://github.com/comfyanonymous/ComfyUI/commit/2c4e92a98b8338f754855a0db7dce164945e366e

If you update your ComfyUI and try again, hopefully your error will go away.

**Comment by andrewlabx** [comment]
I confirm, after updating a second tme my confyui, there is no longer any error.
Thanks for your time and help on this.
