### ISSUE TITLE
Where do I put ControlNet models?

### ISSUE THREAD

**Issue by norton-chris** [Kosinkadink/ComfyUI-Advanced-ControlNet#57]
Dumb question but where do I put ControlNet models?

I've tried a bunch of different locations. There is no models folder inside the ComfyUI-Advanced-ControlNet folder which is where every other extension stores their models. I just see undefined in the Load Advanced ControlNet Model node.

Seems like a super cool extension and I'd like to use it, thank you for your work!

**Comment by Kosinkadink** [comment]
Use the default ComfyUI controlnet directory: ```ComfyUI/models/controlnet```

**Comment by norton-chris** [comment]
Thanks!
