### ISSUE TITLE
ControlLora support broken after last PR

### ISSUE THREAD

**Issue by Kosinkadink** [Kosinkadink/ComfyUI-Advanced-ControlNet#6]
Working on it now

**Comment by Kosinkadink** [comment]
Should be fixed now with latest commit.

**Comment by suede299** [comment]
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/85022330/fcaa8cad-67ff-4fb4-b50b-159a38f2295f)
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/85022330/528d3e34-5350-4c9c-8346-dc2e158bf919)
This commit doesn't seem to have solved the problem of loading the controllora

**Comment by Kosinkadink** [comment]
Ah, I see, ControlLora inherits from ControlNet, so isinstance thinks they're the same - will push out fix in a few minutes

**Comment by Kosinkadink** [comment]
Ok, should be fixed now - it should leave ControlLora completely alone now and not accidentally confuse it for ControlNet class.
