### ISSUE TITLE
Load SparseCtrl Model cause error

### ISSUE THREAD

**Issue by tomudo** [Kosinkadink/ComfyUI-Advanced-ControlNet#63]
I use Load SparseCtrl Model with animateDiff_v3_sd15_sparsectl_scibble.ckpt that download from comfyUi Manager but it cause error when KSampler node process.
It show error "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!".

How could I fix it ?

**Comment by tomudo** [comment]
I found it is not compatible with --novram option in start command line. It works with --lowvram. May dev investigate in this problem?

**Comment by Kosinkadink** [comment]
Thanks for the report, I'll look into it over the next few days!

**Comment by Kosinkadink** [comment]
I think the issue should now be fixed as of an update I did last week - if it is not fixed, feel free to reopen the issue.
