### ISSUE TITLE
[ Feature Request ] Requesting the Multi-Controlnet feature for use with AnimateDiff Comfyui

### ISSUE THREAD

**Issue by Ketorami** [Kosinkadink/ComfyUI-Advanced-ControlNet#7]
I noticed that AnimateDiff for ComfyUI works well when using just a single Controlnet. However, when I tried using other nodes to combine multiple Controlnets, I couldn't get the AnimateDiff node to work. It's really disappointing that I can only use it with a single Controlnet. So, I would like to ask if you have any plans to develop a Multi-Controlnet Node for ComfyUI AnimateDiff. It's truly unfortunate that Multi-Controlnet doesn't seem to work for AnimateDiff.

**Comment by Kosinkadink** [comment]
Can you send me an example of one of your workflows? People have been using like half a dozen controlnets at a time with Kosinkadink/ComfyUI-AnimateDiff-Evolved without issue so far. You don't need to combine controlnets to combine them, the typical usage is chaining them together.

**Comment by Kosinkadink** [comment]
You can chain control nets together by plugging the positive and negative conditioning of one controlnet into the next. See if that works for you as a replacement for the multicontrolnet node. I'd share a quick screenshot, but I'm not home rn.
