### ISSUE TITLE
`Load Advanced Controlnet` node not available -  only `Apply Advanced Controlnet`

### ISSUE THREAD

**Issue by dangerweenie** [Kosinkadink/ComfyUI-Advanced-ControlNet#72]
`Load Advanced Controlnet` node not available -  only `Apply Advanced Controlnet` 

is this expected behavior?  I've installed it twice and the former node is missing from ComfyUI

**Comment by Kosinkadink** [comment]
Something was likely up in your environment, or you needed to refresh your browser tab after updating. Assuming you've already figured it out after 3 months, I'll close the issue.
