### ISSUE TITLE
pinokio/api/comfyui.git/app/main.py': [Errno 2] No such file or directory (env) bash-3.2$ 

### ISSUE THREAD

**Issue by rhinoxu** [Kosinkadink/ComfyUI-Advanced-ControlNet#80]
The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
bash-3.2$ source /Volumes/2T/pinokio/api/comfyui.git/app/env/bin/activate /Volumes/2T/pinokio/api/comfyui.git/app/env && python main.py --cpu
python: can't open file '/Volumes/2T/pinokio/api/comfyui.git/app/main.py': [Errno 2] No such file or directory
(env) bash-3.2$ 
![截屏2024-03-08 11 10 57](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/57742190/5a768f54-ac6f-4b97-a422-7cd932c835de)

如何解决mac

**Comment by Kosinkadink** [comment]
Unrelated to Advanced-ControlNet, hope you were able to get stuff working on your end. Closing issue.
