### ISSUE TITLE
can  not  bypass controlnet 

### ISSUE THREAD

**Issue by bihailantian655** [Kosinkadink/ComfyUI-Advanced-ControlNet#90]
![workflow (6)](https://github.com/rgthree/rgthree-comfy/assets/35267721/502ba749-fd5d-4544-9276-fc20ba226775)
![workflow (5)](https://github.com/rgthree/rgthree-comfy/assets/35267721/f2a9c2c2-f59f-4c77-b67f-214ff998cdc1)

the only difference between these two  pic is whether or not to bypass a cnet  group .   here  is   one  more  pic  

![workflow (7)](https://github.com/rgthree/rgthree-comfy/assets/35267721/ac83b327-5fdd-47ce-a83e-14ccee60f542)

I don't think this is a fault with [rgthree-comfy] , but I am unsure who to report this issue to.

**Comment by bihailantian655** [comment]
It seems that bypassing the cnet still affects the generated images, causing them to become blurry.

**Comment by Kosinkadink** [comment]
I have no custom JavaScript in this repo, so the bug of bypass not working is due to something else. I've never had any problem with bypass if I do vanilla ComfyUI bypass.

**Comment by bihailantian655** [comment]
![workflow (8)](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/35267721/7847ab23-bd08-46e8-b24e-48e8e55b1251)

**Comment by Kosinkadink** [comment]
Might be a weird .js issue with grouped nodes (that cnet node does not look like it's individual, it looks like the two nodes merged into one)

**Comment by Kosinkadink** [comment]
Either way, nothing I can do about it, it's a bug somewhere else. The CNs you're loading are basic controlnet types from the looks of it, so they should work as intended. Bypassing not working is a JavaScript problem, and since I do no JavaScript in this repo, it can't be an issue with the nodes here.

**Comment by Kosinkadink** [comment]
There is a bug currently with nodes merged into one not always properly respecting the positive/negative conditioning, so this might be related to do. Try it with no merged nodes.

**Comment by bihailantian655** [comment]
by  using  advanced  cnet   have no  such issue. but  i  dont  know  why   the  second  sampler   can  not  preview  image


    
![workflow (9)](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/35267721/2fdcc1ac-63dd-4da0-ba72-4f8f5d6c7693)    weird   weird

**Comment by bihailantian655** [comment]
forget   connect  vae t  the second  sampler
